version: '3.8'

services:
  couchdb:
    image: couchdb
    container_name: hospitalrun
    ports:
      - "5984:5984"
    environment:
      - COUCHDB_USER=admin
      - COUCHDB_PASSWORD=password

  mongo:
    image: mongo
    restart: always
    environment:
      MONGO_INITDB_DATABASE: hospitalrun
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: password